### ISSUE TITLE
Higher order components should be wrapped before render()

### ISSUE THREAD

**Issue by gaearon** [krasimir/react-in-patterns#12]
This is **not** a good example:

```js
var OriginalComponent = () => <p>Hello world.</p>;

class App extends React.Component {
  render() {
    return React.createElement(enhanceComponent(OriginalComponent));
  }
};
```

It is slow and blows away the DOM and state completely in all components below `OriginalComponent` because `enhanceComponent(OriginalComponent)` gives you a different type every time you `render()`.

Here’s how to fix:

```js
var OriginalComponent = () => <p>Hello world.</p>;
var EnhancedComponent = enhanceComponent(OriginalComponent);

class App extends React.Component {
  render() {
    return React.createElement(EnhancedComponent);
  }
};
```

The trick? We do this just once, so `render()` always returns the same type of `EnhancedComponent`.

**Comment by krasimir** [comment]
Fixed. Thanks for the feedback @gaearon.

**Comment by gaearon** [comment]
👍 Thanks for quick fix.

**Comment by gaoqiang19514** [comment]
When can I be as good as you？
