### ISSUE TITLE
We need to write about container vs presentational components

### ISSUE THREAD

**Issue by antoaravinth** [krasimir/react-in-patterns#2]
The title says it all.. If you don't find time, let me know I can work on the week end :)

**Comment by krasimir** [comment]
Ah that's interesting. Can you give me an example of a container (I feel that it's close to higher-order component) and presentational components (do you mean a stateless component).

**Comment by JoshAddington** [comment]
Container components are usually connected to Flux stores and contain all of the business logic. Presentational components are then used to display data that is passed down to them as props. 

It helps to make the presentational components more reuseable, as they aren't tied to a certain part of the data store.

Here's an article Dan Abramov wrote about it. [Presentational and Container Components
](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.llu29efvo)

**Comment by krasimir** [comment]
Nice. Thanks. I'll prepare a PR and will probably poke you and @gaearon when it's done.

**Comment by 11th** [comment]
Definitely good idea.

I use this pattern for almost every component. Also I have pattern how to combine these 2 files/components.

Let's say my component is Counter.
First I create `components/Counter` folder.
Next the container/logic component goes into `Counter/index.cjsx` file.
And the view/presentation component goes into `Counter/view.cjsx`.

I combine them like this:

```cjsx
### Counter/index.cjsx
React = require 'react'
Counter = require './view'

CounterContainer = React.createClass

  getInitialState: ->
    value: 0

  handleClick: ->
    @setState
      value: @state.value + 1

  render: ->
    <Counter
      onClick={@handleClick}
      value={@state.value}
    />
```

```cjsx
### Counter/view.cjsx
React = require 'react'

Counter = React.createClass

  propTypes:
    value: React.PropTypes.number.isRequired
    onClick: React.PropTypes.func.isRequired

  render: ->
    <button onClick={@props.onClick}>{@props.value}</button>
```

Then you just require the component like 
```cjsx
Counter = require 'components/Counter'
ReactDOM.render <Counter />, document.getElementById 'app'
```
and the require function will resolve to that `index.cjsx` which you want. It's similar/same with JSX/Babel. I used CoffeeScript for brevity.

Note that for brevity I don't name tie presentational component like CounterView. I find it too explicit (react is for views), so implicitly I consider every component plain/presentational, and otherwise, if it has logic I append Container/Controller to its name.

Hope it helps.

**Comment by antoaravinth** [comment]
And also starting your project with Container components are good in a way, if you choose to flux/redux down the line. Since designing with Container components you will be handling all the states into them, leaving Presentational components to receive the props. Thus Presentational components become stateless and they are easy to reason and resuse as well. Since I'm from Java background, making Presentational along with `propTypes` makes a good interface of your view. Making interfaces of such kind is way good in documenting your views itself!

The idea works pretty well unless your data needs to be splitted into two different views (where the Container component is not a parent) where in which you need to bring in a store. Now since all Presentational components don't have state, you need to touch only Container Components and wrap that with redux bindings to make your system works with redux. 

I love this approach as its easy to start only with knowledge of React, gives a good use case where you will need Redux and also easy to move to redux!

**Comment by krasimir** [comment]
@antoaravinth @JoshAddington @11th @gaearon Finally I finished "Presentational and containers" section https://github.com/krasimir/react-in-patterns/tree/master/patterns/presentational-and-container

Feedback is more than welcome.

**Comment by 11th** [comment]
Great job!

**Comment by dan13more** [comment]
@11th @krasimir question: so if the rule is that the container is the component that renders the view, can you have more than 1 container (for whatever UI/UX related reason) "associated" with 1 presentational/dumb component?

**Comment by krasimir** [comment]
@dan13more yep, I think it's a valid point. If you have such a case then it means that you did a good job with that container. If it works with more then one presentational component.

**Comment by antoaravinth** [comment]
@krasimir Looks good. If you have plan to write about redux, there you can mention like how its easy to move container components to a component mapped with redux connect leaving other presentational component behave the same.

**Comment by krasimir** [comment]
@antoaravinth good point. I'll make a note about that. And yes, I should add a redux section.

**Comment by antoaravinth** [comment]
@krasimir : Probably can I write that note if you don't mind :)

**Comment by krasimir** [comment]
Yep!
