### ISSUE TITLE
One-way direction data flow question

### ISSUE THREAD

**Issue by thanhvg** [krasimir/react-in-patterns#21]
In 'One-way direction data flow', Store provides subscription for change. Does Store also need to implement unsubscription for component App to call it inside  componentWillUnmount to unsubscribe?

**Comment by AllenFang** [comment]
> Does Store also need to implement unsubscription

I think it's necessary. For example, `redux` also support this feature. for example:
```js
let unsubscribe = store.subscribe(() =>
  console.log(store.getState())
)

//...

unsubscribe()
```

**Comment by ywwhack** [comment]
Agree with @AllenFang 
If you use `react-redux` lib，it does this free for you https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L167

**Comment by AllenFang** [comment]
@ywwhack nice share, `react-redux` did it for you so that you dont unsubscribe in your container.

**Comment by krasimir** [comment]
These are very good points.
