### ISSUE TITLE
Using React's context (prior v. 16.3) section needs warning

### ISSUE THREAD

**Issue by brownieboy** [krasimir/react-in-patterns#23]
React's context prior to 16.3  is undocumented and not recommended by Facebook.  But you don't warn the reader of this until the start of the **Using React's context (v. 16.3 and above)** section, by which time they may well have worked their way through that **prior v. 16.3** section, and would now be wondering "why did I just waste my time learning that?"

I think you need add a warning at the start of the **prior v. 16.3** section.

**Comment by krasimir** [comment]
I added a sentence in the beginning of the `Using React's context (prior v. 16.3)` section.

Also In version prior 16.3 the API was documented pretty well. They just didn't recommend it. But in practice all the major libraries were using that API for its DI so I felt that I had to add this into the book. 

*I also started the book way back when that was the only one API available :)*
