### ISSUE TITLE
If it's OK to let me translate this awesome book into Chinese?

### ISSUE THREAD

**Issue by hateonion** [krasimir/react-in-patterns#29]
Hi This book is quite awesome!
If it's OK to let me translate it into Chinese? 
Just want to share this with more people.

**Comment by krasimir** [comment]
Hey, yep. Feel free to translate it. Just let me know when it's done so we can update the README. Or directly submit a PR.

**Comment by hateonion** [comment]
Awesome! Thanks Mate!
