### ISSUE TITLE
chapter 3 next button

### ISSUE THREAD

**Issue by destradafilm** [krasimir/react-in-patterns#31]
If you click next page on https://krasimir.gitbooks.io/react-in-patterns/content/chapter-2/#output it takes you back to https://krasimir.gitbooks.io/react-in-patterns/content/chapter-2/#input

**Comment by krasimir** [comment]
Hm ... yep. Sorry, it's not me generating the web version of the book. It's GitBook so I can't really fit. Or at least I don't know how. I'll investigate later this week. Thanks for reporting.

**Comment by destradafilm** [comment]
No prob, very informative book so far! thanks for creating this
