### ISSUE TITLE
Add leading zero to chapter names

### ISSUE THREAD

**Issue by maracuja-juice** [krasimir/react-in-patterns#37]
The sorting of the chapters currently is like this:
```
chapter-1
chapter-10
chapter-11
chapter-12
chapter-13
chapter-2
chapter-3
...
```
This doesn't feel natural. If the chapters with a number below 10 had a leading zero it would be sorted in the correct way:
```
chapter-01
chapter-02
chapter-03
chapter-04
...
chapter-09
chapter-10
...
```
So I suggest that all chapters below 10 get a leading zero added before their number.

**Comment by lnfnunes** [comment]
🖐 working on it...

**Comment by krasimir** [comment]
Merged.
