### ISSUE TITLE
In Chapter 8, the mixins link does not contain the content

### ISSUE THREAD

**Issue by pakaponk** [krasimir/react-in-patterns#56]
React has moved the mixins content to this link instead [https://reactjs.org/docs/react-without-es6.html#mixins](https://reactjs.org/docs/react-without-es6.html#mixins). 
Should we update it to the new one instead.

**Comment by krasimir** [comment]
Yep, can you open the PR against the repo here.

**Comment by pakaponk** [comment]
@krasimir #57
