### ISSUE TITLE
High-order component example does not return the enhanced component

### ISSUE THREAD

**Issue by dennisXZX** [krasimir/react-in-patterns#59]
In the High-order example, it seems we forget to return the enhanced component.

```js
var enhanceComponent = (Component) => {
  class Enhance extends React.Component {
    render () {
      return (
        <Component {...this.props} />
      )
    }
  }
  
  // should we return the component here?
  return Enhance;
}
```

**Comment by lnfnunes** [comment]
Actually, the example don't have the brackets after the => as you mentioned
![image](https://user-images.githubusercontent.com/2450417/46973687-5c7b7000-d098-11e8-96e0-55e7e78718fe.png)
So, the class is being returned correctly by the arrow function!

@dennisXZX There are any other example that I didn´t find?
If not, I think you can close this issue...

**Comment by krasimir** [comment]
@infertux good call. I was going to work on this issue today but you were first. @dennisXZX is that example that you are referring to?

**Comment by dennisXZX** [comment]
@infertux thanks guys! Sorry, I am new to React I didn't know that would return the class. TIL~ Thanks again. I will close the issue.
