### ISSUE TITLE
Can i help translate this repo to Vietnamese for support our community

### ISSUE THREAD

**Issue by hprobotic** [krasimir/react-in-patterns#8]
Hi mates

I really excited and wanna translate this repo to Vietnamese for help our React developer community in Vietnam
Can i create new pull request or fork new repo 💃

**Comment by krasimir** [comment]
This sounds really good. The only one thing that worries me is the fact that I/we are going to change the content often in the next few weeks. I don't mind of course merging such PR. It's just possible that we have different content in README.md versus README-vi.md.

**Comment by hprobotic** [comment]
Thanks for response

I think, i should create new branch and just merge PR when somethings done. And of course, i will notice you about PR when we must it to master

**Comment by krasimir** [comment]
+1 Let's go with this.

**Comment by johandally** [comment]
Lets go
